language: objective-c

env:
    global:
        - PROJECT_PATH="TestTravis.xcodeproj"
        - DEVICE="iPhone Retina (3.5-inch)"
        - VERSION="7.0"
        - PASSWORD="unused" # Currently Travis works without a password but this may change.
        - OUTPUT_DIR="output"

before_install:
    # Travis will automatically install git submodules
    - echo "travis variable = $TRAVIS"
    - rake install --rakefile Integration\ Tests/Subliminal/Rakefile DOCS=no

script: >
    "Integration Tests/Subliminal/Supporting Files/CI/subliminal-test"
    -project "$PROJECT_PATH"
    -sim_device "$DEVICE"
    -sim_version "$VERSION"
    -login_password "$PASSWORD"
    -output "$OUTPUT_DIR"